### ISSUE TITLE
Grid collapsed after save

### ISSUE THREAD

**Issue by IRIDON** [akilli/ck4#2]
Hi, i have a problem in my site and yours demo.

Create two column http://tinyurl.com/y2uhppw6, after save all column collapsed http://tinyurl.com/y5osrve8

**Comment by akilli** [comment]
Hi Iridon,

what is actually your problem? I don't see a problem in your screenshots. You have read the README.md of the Grid Widget?

> This widget will only allow other widgets as child elements. The filtering now takes place on `downcast`.

**Comment by IRIDON** [comment]
Emmm, it's allow only other widgets?

**Comment by akilli** [comment]
Yes.

**Comment by IRIDON** [comment]
Sorry for my inattention. Thank

**Comment by akilli** [comment]
No problem. 

It'd be interesting to know, what you tried to achieve.

**Comment by IRIDON** [comment]
I have Django website, and a want to add gallery or something like that in page content.

**Comment by IRIDON** [comment]
How do I understand the problem, because the file manager I use, adds pictures without a tag <figure>

**Comment by akilli** [comment]
Yes, that is the problem as the `img`-element is surely no widget. You could either use a widget like p.e. [media](https://ckeditor.com/cke4/addon/media) or hack the [downcast method](https://github.com/akilli/ck4/blob/master/grid/plugin.js#L51-L76) to allow all/more elements.

By the way, for a gallery you could also use the [gallery widget](https://ckeditor.com/cke4/addon/gallery). But this would not solve your problem, because the gallery widget is even more strict and only allows figure widgets. Sorry ;-)
